// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yauedvufzkrwmydtejgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdWVkdnVmemtyd215ZHRlamd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjY2ODcsImV4cCI6MjA2MjgwMjY4N30.4epgMizXC1b6unRSoz0pWr6knw5i7gopyAZrOd4hLGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);